"""Mapeamento de colunas do CSV NHANES para a tabela do Supabase."""

CSV_TO_DB: dict[str, str] = {
    "SEQN": "seqn",
    "Protein": "protein",
    "Carbohydrates": "carbohydrates",
    "Sugars": "sugars",
    "Fiber": "fiber",
    "Saturated_Fat": "saturated_fat",
    "Monounsaturated_Fat": "monounsaturated_fat",
    "Polyunsaturated_Fat": "polyunsaturated_fat",
    "Cholesterol": "cholesterol",
    "Beta_Carotene": "beta_carotene",
    "Cryptoxanthin": "cryptoxanthin",
    "Lutein_Zeaxanthin": "lutein_zeaxanthin",
    "Thiamin": "thiamin",
    "Riboflavin": "riboflavin",
    "Niacin": "niacin",
    "Vitamin_B6": "vitamin_b6",
    "Folic_Acid": "folic_acid",
    "Food_Folate": "food_folate",
    "Vitamin_B12": "vitamin_b12",
    "Vitamin_C": "vitamin_c",
    "Vitamin_D": "vitamin_d",
    "Vitamin_E": "vitamin_e",
    "Vitamin_K": "vitamin_k",
    # O CSV local rotula esta coluna como "Iron", mas os valores seguem a
    # posicao/formula do NHANES para folato DFE, nao ferro alimentar.
    "Iron": "folate_dfe",
    "Choline": "choline",
    "Calcium": "calcium",
    "Phosphorus": "phosphorus",
    "Magnesium": "magnesium",
    "Zinc": "zinc",
    "Copper": "copper",
    "Sodium": "sodium",
    "Potassium": "potassium",
    "Selenium": "selenium",
    "Theobromine": "theobromine",
    "Moisture": "moisture",
    "Congestive": "congestive",
    "Coronary": "coronary",
    "Heart_attack": "heart_attack",
    "Stroke": "stroke",
    "Angina": "angina",
    "Age": "age",
    "BMI": "bmi",
    "Waist_circ": "waist_circ",
    "Systolic_BP": "systolic_bp",
    "Diastolic_BP": "diastolic_bp",
    "Total_Colesterol": "total_cholesterol",
    "C_Reactive": "c_reactive",
}

CVD_COLUMNS = ["congestive", "coronary", "heart_attack", "stroke", "angina"]
